<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TikTok</name>
   <tag></tag>
   <elementGuidId>2c7a1644-ba9d-4c07-9149-5a7b32a1da7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[27]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ek-custom-dropdown-list._vwo_coal_1709287011420.vwo_loaded.vwo_loaded_80</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;TikTok &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7994ba4f-a929-466b-b49e-1f9c7b84f7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efbc1806-ad2d-4e4a-9d02-3602e96e2648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ek-custom-dropdown-list _vwo_coal_1709287011420 vwo_loaded vwo_loaded_80</value>
      <webElementGuid>6e63fc70-94d9-4954-a9c6-d0ffc7aac1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TikTok</value>
      <webElementGuid>d2352ac2-72ea-40ce-b637-d732cd18ba62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-content-planner&quot;]/div[@class=&quot;d-flex justify-content-between mb-2&quot;]/div[1]/div[@class=&quot;dropdown&quot;]/button[@class=&quot;ek-custom-dropdown-list _vwo_coal_1709287011420 vwo_loaded vwo_loaded_80&quot;]</value>
      <webElementGuid>78d78d1e-949c-42a2-9263-704842da68f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[27]</value>
      <webElementGuid>6180986f-8423-4c5f-8ce8-a5398f96b010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>f08aa679-26ff-4d09-b65b-3ec9f80f482f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post Insights'])[1]/following::button[1]</value>
      <webElementGuid>b0ccdce9-e71a-4441-948c-cb0d17f97dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule a post'])[1]/following::button[1]</value>
      <webElementGuid>c08f6113-f67d-4242-8cf7-266301b4a6bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Account to access your latest analytics summary'])[1]/preceding::button[2]</value>
      <webElementGuid>cd7a1455-0311-4632-8bc1-6f895581da76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>f1566ef8-85a9-4c6e-b369-d532d17275e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'TikTok' or . = 'TikTok')]</value>
      <webElementGuid>ce511198-17d1-4ebd-8adb-9df17a28378c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
