<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_url</name>
   <tag></tag>
   <elementGuidId>51c276a3-faa6-4fab-8727-5a4ebe624931</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='https://www.youtube.com/watch?v=7QXDnWRy6MI&amp;list=RD7QXDnWRy6MI&amp;start_radio=1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;url&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Insert Youtube video link&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d19038c2-0402-4117-88c1-0f3b631ad56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>6daffb6a-10ff-45bd-b701-a7ba86f31632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert Youtube video link</value>
      <webElementGuid>a47d2ff5-caef-4a8f-8db7-d17b87d2d9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://www.youtube.com/watch?v=7QXDnWRy6MI&amp;list=RD7QXDnWRy6MI&amp;start_radio=1</value>
      <webElementGuid>4b8fa574-a5aa-4e0e-9dbf-4e02d6d730ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams ek-streams-page&quot;]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;ek-stream-list&quot;]/div[@class=&quot;import-video-container d-flex flex-column justify-content-center align-items-center&quot;]/div[@class=&quot;video-input-container d-flex justify-content-center align-items-center my-2 w-100 w-md-75&quot;]/input[1]</value>
      <webElementGuid>4ebab29a-650a-42d6-b978-d92ad5f9c1d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='https://www.youtube.com/watch?v=7QXDnWRy6MI&amp;list=RD7QXDnWRy6MI&amp;start_radio=1']</value>
      <webElementGuid>d6ef4454-ecb8-48d7-89bb-1846c1992ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>d2fdb0dd-c80e-405b-ae5f-4442a4065774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>989e91f7-9994-4a39-846a-e51760681952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'url' and @placeholder = 'Insert Youtube video link']</value>
      <webElementGuid>16265b5a-963f-41b6-b8e5-e907e377c494</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
