<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NEWEST TO OLDESTOLDEST TO NEWEST</name>
   <tag></tag>
   <elementGuidId>60780760-2874-418c-96d4-8642f6f1e10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='soft_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#soft_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#soft_type >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23c77195-50c0-4829-9d7b-3a1437ceff17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-sort-by show-desktop</value>
      <webElementGuid>ab428c88-1554-48fd-8157-639eda0e9502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>soft_type</value>
      <webElementGuid>84118530-eed6-49c5-88b5-40d8ce06efc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>soft_type</value>
      <webElementGuid>7afe66ee-b61d-4d45-8798-19b6f25b0f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NEWEST TO OLDESTOLDEST TO NEWEST</value>
      <webElementGuid>a86efc6c-3008-4e38-803e-f1736e48451c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;ek-dashboard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;container-children-dashboard&quot;]/div[@class=&quot;ek-streams&quot;]/div[3]/div[@class=&quot;ek-edited-video&quot;]/div[2]/div[@class=&quot;content&quot;]/div[1]/select[@id=&quot;soft_type&quot;]</value>
      <webElementGuid>0be3d7ab-ff6d-4efb-a4f4-516cc8e27ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='soft_type']</value>
      <webElementGuid>8b24d242-4641-418a-b433-236aa56dc064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div[3]/div/div/div/div[3]/div/div[2]/div/div/select</value>
      <webElementGuid>696a3b47-1b73-41ee-afaf-c40608582155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by:'])[1]/following::select[1]</value>
      <webElementGuid>19dd7b2b-2a41-498d-b8d6-cb3de803b2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::select[1]</value>
      <webElementGuid>5ab83454-51fa-4faa-bd2a-f8330334fc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Edited Clip Yet'])[1]/preceding::select[4]</value>
      <webElementGuid>f3cfa9f0-f806-4990-bafb-d31fc11a44c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You don’t have any edited clip right now. To have one, try to edit one of your available clip now'])[1]/preceding::select[4]</value>
      <webElementGuid>22465c79-41dd-47ec-bac6-da29832c8f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>82f341a7-44c0-4011-8033-7cbee89902cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'soft_type' and @name = 'soft_type' and (text() = 'NEWEST TO OLDESTOLDEST TO NEWEST' or . = 'NEWEST TO OLDESTOLDEST TO NEWEST')]</value>
      <webElementGuid>3308c4cc-0d1f-4915-b51e-84152d500a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
