<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Montages</name>
   <tag></tag>
   <elementGuidId>59f27595-d024-4d00-a79f-e5f9886562ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submenu-3']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submenu-3 > ul > li:nth-of-type(2) > a.sidebar-submenu-link > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Montages&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6be61608-4e00-4906-b8b4-8797395a8975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Montages</value>
      <webElementGuid>87acf54b-34e8-4ad3-8edb-ce9f3f8331d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-3&quot;)/ul[1]/li[2]/a[@class=&quot;sidebar-submenu-link&quot;]/span[1]</value>
      <webElementGuid>a441e4dd-4ffe-489b-9568-10c229460161</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submenu-3']/ul/li[2]/a/span</value>
      <webElementGuid>17cbf8f6-f9b0-47f5-8988-56ebcd5d207e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edited Clips'])[1]/following::span[1]</value>
      <webElementGuid>4ccdd45e-aa2a-4cb1-9c93-808c639bde5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edits'])[1]/following::span[2]</value>
      <webElementGuid>a6c5f8d1-df4d-44b1-83cf-b7d9a3ff1f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time-saving Tools'])[1]/preceding::span[2]</value>
      <webElementGuid>87e38177-e94f-4ac5-8af0-699aee61d422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request a Pro'])[1]/preceding::span[3]</value>
      <webElementGuid>6bfb5e91-042f-4344-93de-6cc2aaf55208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Montages']/parent::*</value>
      <webElementGuid>51fa2749-75e0-483d-b0b7-52534c93b7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li[2]/a/span</value>
      <webElementGuid>28cc64f7-17b0-4756-a5be-11f90cc7a097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Montages' or . = 'Montages')]</value>
      <webElementGuid>8a0dc0c4-f552-479a-bc9c-4f07b44a9437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional Edits'])[1]/preceding::span[3]</value>
      <webElementGuid>85ac52cc-d82d-48e1-bc08-5927900babb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
