<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_StreamVideo</name>
   <tag></tag>
   <elementGuidId>efe16805-77a1-4534-bfae-6dbdef700e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submenu-1']/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sidebar-submenu-link > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Stream/Video&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21eb05d4-e921-4f74-9ec3-87d422a302f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stream/Video</value>
      <webElementGuid>7e868a17-612c-473e-b52a-15157ada7ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-1&quot;)/ul[1]/li[1]/a[@class=&quot;sidebar-submenu-link&quot;]/span[1]</value>
      <webElementGuid>fa6a19a0-4389-4073-a649-082b9afada7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='submenu-1']/ul/li/a/span</value>
      <webElementGuid>56733d99-7119-4a33-a09f-71de0cf6e3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clip Library'])[1]/following::span[1]</value>
      <webElementGuid>3bedda4c-6f77-453c-8c00-e24db4cc3afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[2]</value>
      <webElementGuid>bf68e3f4-096c-48e5-8ed9-6b5702d4d509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitch/Kick Clips'])[1]/preceding::span[1]</value>
      <webElementGuid>c381f0fe-c459-4934-8ac4-9788834b0a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Playlist'])[1]/preceding::span[2]</value>
      <webElementGuid>3edc6aec-4685-4cd7-bb58-e62c9894b91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stream/Video']/parent::*</value>
      <webElementGuid>5031eb5d-0a75-448f-a4ae-83441cb8b18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/span</value>
      <webElementGuid>62577403-4926-4d8e-aea9-822a28ac7431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Stream/Video' or . = 'Stream/Video')]</value>
      <webElementGuid>914b519b-cd98-4cd6-940f-83a9692bbb13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
